import test from "node:test";
import assert from "node:assert/strict";
import { validateQuiz } from "../quiz-validation.js";

const validQuiz = { id: "quiz", title: "Quiz", rounds: [{ id: "round-1", title: "Round", questions: [{ id: "question-1", type: "single_choice", prompt: "Question?", points: 1, options: [{ id: "a", label: "A" }, { id: "b", label: "B" }], correctOptionIds: ["a"] }] }] };
test("valid choice quiz passes author validation", () => assert.deepEqual(validateQuiz(validQuiz), []));
test("duplicate question IDs and bad answer keys fail validation", () => { const invalid = structuredClone(validQuiz); invalid.rounds[0].questions.push({ ...invalid.rounds[0].questions[0], correctOptionIds: ["missing"] }); const errors = validateQuiz(invalid); assert.match(errors.join(" "), /duplicate question ID/); assert.match(errors.join(" "), /invalid answer key/); });
test("missing title, prompt, or points block publication", () => { const invalid = structuredClone(validQuiz); invalid.title = ""; invalid.rounds[0].questions[0].prompt = ""; invalid.rounds[0].questions[0].points = 0; const errors = validateQuiz(invalid); assert.match(errors.join(" "), /Quiz title is required/); assert.match(errors.join(" "), /needs a player prompt/); assert.match(errors.join(" "), /needs positive points/); });
test("closest-number questions require a finite target", () => { const quiz = structuredClone(validQuiz); quiz.rounds[0].questions[0] = { id: "closest", type: "closest_number", prompt: "How many?", points: 3, targetNumber: 42 }; assert.deepEqual(validateQuiz(quiz), []); quiz.rounds[0].questions[0].targetNumber = "not a number"; assert.match(validateQuiz(quiz).join(" "), /valid target number/); });
test("matching questions use points per pair instead of question points", () => { const quiz = structuredClone(validQuiz); quiz.rounds[0].questions[0] = { id: "matching", type: "matching", prompt: "Match these", pointsPerPair: 1, clips: [{ id: "one", label: "One" }, { id: "two", label: "Two" }], options: [{ id: "a", label: "A" }, { id: "b", label: "B" }], correctPairs: { one: "a", two: "b" } }; assert.deepEqual(validateQuiz(quiz), []); });
test("title-page captions are validated as bounded normalized cues", () => { const quiz = structuredClone(validQuiz); quiz.titlePage = { audio: { captionSourceName: "theme.ass", captions: [{ startMs: 0, endMs: 1200, text: "Hello", karaoke: [{ startMs: 0, endMs: 500, startIndex: 0, endIndex: 5 }] }] } }; assert.deepEqual(validateQuiz(quiz), []); quiz.titlePage.audio.captions[0].karaoke[0].endIndex = 6; assert.match(validateQuiz(quiz).join(" "), /captions/); });
test("title-page presenter is an optional bounded string", () => { const quiz = structuredClone(validQuiz); quiz.titlePage = { presenter: "Team Trivia presents" }; assert.deepEqual(validateQuiz(quiz), []); quiz.titlePage.presenter = 42; assert.match(validateQuiz(quiz).join(" "), /presenter/); });
test("multi-blank audio questions require accepted answers and points per blank", () => { const quiz = structuredClone(validQuiz); quiz.rounds[0].questions[0] = { id: "audio-blanks", type: "multi_fill_in_the_blank", prompt: "Name each title", pointsPerBlank: 5, clips: [{ id: "one", label: "Intro 1", acceptedAnswers: ["Song One"] }, { id: "two", label: "Intro 2", acceptedAnswers: ["Song Two", "Song Too"] }] }; assert.deepEqual(validateQuiz(quiz), []); quiz.rounds[0].questions[0].clips[1].acceptedAnswers = []; assert.match(validateQuiz(quiz).join(" "), /accepted answers for every clip/); });

// The rules below used to live only in author.js's private copy of validateQuiz.
// They are the rules that actually gate Publish, so they belong in the shared
// module every surface and every test uses.
const UUID = "5f6a1b2c-3d4e-4f50-8a9b-0c1d2e3f4a5b";
test("unsupported question types are rejected", () => { const quiz = structuredClone(validQuiz); quiz.rounds[0].questions[0].type = "spelling_bee"; assert.match(validateQuiz(quiz).join(" "), /unsupported question type/); });
test("fill-in-the-blank questions need accepted answers for every blank", () => { const quiz = structuredClone(validQuiz); quiz.rounds[0].questions[0] = { id: "blanks", type: "fill_in_the_blank", prompt: "___ is the title", points: 2, blanks: [{ acceptedAnswers: ["Answer"] }] }; assert.deepEqual(validateQuiz(quiz), []); quiz.rounds[0].questions[0].blanks = []; assert.match(validateQuiz(quiz).join(" "), /accepted answers for every blank/); quiz.rounds[0].questions[0].blanks = [{ acceptedAnswers: [" "] }]; assert.match(validateQuiz(quiz).join(" "), /accepted answers for every blank/); });
test("arrange-in-order questions need a complete unique order key", () => { const quiz = structuredClone(validQuiz); quiz.rounds[0].questions[0] = { id: "order", type: "arrange_in_order", prompt: "Order these", points: 2, items: [{ id: "one", label: "First" }, { id: "two", label: "Second" }], correctOrder: ["one", "two"] }; assert.deepEqual(validateQuiz(quiz), []); quiz.rounds[0].questions[0].correctOrder = ["one", "one"]; assert.match(validateQuiz(quiz).join(" "), /complete, unique order answer key/); quiz.rounds[0].questions[0].correctOrder = ["one", "missing"]; assert.match(validateQuiz(quiz).join(" "), /complete, unique order answer key/); });
test("categorize questions need exactly two categories and a resolvable assignment key", () => { const quiz = structuredClone(validQuiz); quiz.rounds[0].questions[0] = { id: "sorting", type: "categorize", prompt: "Sort these", points: 2, categories: [{ id: "cat-a", label: "A" }, { id: "cat-b", label: "B" }], items: [{ id: "item-1", label: "One" }, { id: "item-2", label: "Two" }], correctCategories: { "item-1": "cat-a", "item-2": "cat-b" } }; assert.deepEqual(validateQuiz(quiz), []); quiz.rounds[0].questions[0].correctCategories["item-2"] = "cat-c"; assert.match(validateQuiz(quiz).join(" "), /two categories and a complete valid assignment key/); quiz.rounds[0].questions[0].correctCategories["item-2"] = "cat-b"; quiz.rounds[0].questions[0].categories.push({ id: "cat-c", label: "C" }); assert.match(validateQuiz(quiz).join(" "), /two categories and a complete valid assignment key/); });
test("matching pair keys must resolve to real option IDs", () => { const quiz = structuredClone(validQuiz); quiz.rounds[0].questions[0] = { id: "matching", type: "matching", prompt: "Match these", pointsPerPair: 1, clips: [{ id: "one", label: "One" }, { id: "two", label: "Two" }], options: [{ id: "a", label: "A" }, { id: "b", label: "B" }], correctPairs: { one: "a", two: "missing" } }; assert.match(validateQuiz(quiz).join(" "), /complete clips, options, pair key/); quiz.rounds[0].questions[0].correctPairs.two = "b"; assert.deepEqual(validateQuiz(quiz), []); quiz.rounds[0].questions[0].clips[1].label = ""; assert.match(validateQuiz(quiz).join(" "), /complete clips, options, pair key/); });
test("private audio asset IDs are validated on questions and finale cues", () => { const quiz = structuredClone(validQuiz); quiz.rounds[0].questions[0].audio = { mediaAssetId: UUID }; quiz.finale = { audio: { podium: { mediaAssetId: UUID } } }; assert.deepEqual(validateQuiz(quiz), []); quiz.rounds[0].questions[0].audio.mediaAssetId = "audio-clip"; assert.match(validateQuiz(quiz).join(" "), /invalid private media asset ID/); quiz.rounds[0].questions[0].audio.mediaAssetId = UUID; quiz.finale.audio.podium.mediaAssetId = "not-a-uuid"; assert.match(validateQuiz(quiz).join(" "), /Finale podium has an invalid private audio asset ID/); });
