import test from "node:test";
import assert from "node:assert/strict";
import { validateQuiz } from "../quiz-validation.js";

const validQuiz = { id: "quiz", title: "Quiz", rounds: [{ id: "round-1", title: "Round", questions: [{ id: "question-1", type: "single_choice", prompt: "Question?", points: 1, options: [{ id: "a", label: "A" }, { id: "b", label: "B" }], correctOptionIds: ["a"] }] }] };
test("valid choice quiz passes author validation", () => assert.deepEqual(validateQuiz(validQuiz), []));
test("duplicate question IDs and bad answer keys fail validation", () => { const invalid = structuredClone(validQuiz); invalid.rounds[0].questions.push({ ...invalid.rounds[0].questions[0], correctOptionIds: ["missing"] }); const errors = validateQuiz(invalid); assert.match(errors.join(" "), /duplicate question ID/); assert.match(errors.join(" "), /invalid answer key/); });
test("missing title, prompt, or points block publication", () => { const invalid = structuredClone(validQuiz); invalid.title = ""; invalid.rounds[0].questions[0].prompt = ""; invalid.rounds[0].questions[0].points = 0; const errors = validateQuiz(invalid); assert.match(errors.join(" "), /Quiz title is required/); assert.match(errors.join(" "), /needs a player prompt/); assert.match(errors.join(" "), /needs positive points/); });
test("closest-number questions require a finite target", () => { const quiz = structuredClone(validQuiz); quiz.rounds[0].questions[0] = { id: "closest", type: "closest_number", prompt: "How many?", points: 3, targetNumber: 42 }; assert.deepEqual(validateQuiz(quiz), []); quiz.rounds[0].questions[0].targetNumber = "not a number"; assert.match(validateQuiz(quiz).join(" "), /valid target number/); });
test("matching questions use points per pair instead of question points", () => { const quiz = structuredClone(validQuiz); quiz.rounds[0].questions[0] = { id: "matching", type: "matching", prompt: "Match these", pointsPerPair: 1, clips: [{ id: "one", label: "One" }, { id: "two", label: "Two" }], options: [{ id: "a", label: "A" }, { id: "b", label: "B" }], correctPairs: { one: "a", two: "b" } }; assert.deepEqual(validateQuiz(quiz), []); });
test("title-page captions are validated as bounded normalized cues", () => { const quiz = structuredClone(validQuiz); quiz.titlePage = { audio: { captionSourceName: "theme.ass", captions: [{ startMs: 0, endMs: 1200, text: "Hello", karaoke: [{ startMs: 0, endMs: 500, startIndex: 0, endIndex: 5 }] }] } }; assert.deepEqual(validateQuiz(quiz), []); quiz.titlePage.audio.captions[0].karaoke[0].endIndex = 6; assert.match(validateQuiz(quiz).join(" "), /captions/); });
test("title-page presenter is an optional bounded string", () => { const quiz = structuredClone(validQuiz); quiz.titlePage = { presenter: "Team Trivia presents" }; assert.deepEqual(validateQuiz(quiz), []); quiz.titlePage.presenter = 42; assert.match(validateQuiz(quiz).join(" "), /presenter/); });
test("multi-blank audio questions require accepted answers and points per blank", () => { const quiz = structuredClone(validQuiz); quiz.rounds[0].questions[0] = { id: "audio-blanks", type: "multi_fill_in_the_blank", prompt: "Name each title", pointsPerBlank: 5, clips: [{ id: "one", label: "Intro 1", acceptedAnswers: ["Song One"] }, { id: "two", label: "Intro 2", acceptedAnswers: ["Song Two", "Song Too"] }] }; assert.deepEqual(validateQuiz(quiz), []); quiz.rounds[0].questions[0].clips[1].acceptedAnswers = []; assert.match(validateQuiz(quiz).join(" "), /accepted answers for every clip/); });
