// image-engine.js — Prompt Battle adapter layer.
//
// Pure functions only: no fetching, no side effects, no randomness. This is
// what lets test/image-engine.test.js run entirely from fixtures instead of
// a live provider, which CLAUDE.md forbids in tests. Seeds are generated by
// the caller (the Worker) and passed in, precisely so buildRequests stays
// deterministic.
//
// Contract: docs/superpowers/specs/2026-08-24-prompt-battle-free-engine-addendum.md
// section 2. That addendum corrects the base design's singular
// buildRequest/parseResponse pair (2026-08-17-prompt-battle-design.md
// section 7.3), which cannot express a provider that needs N calls to
// produce N variants without pushing I/O into this module. Each adapter
// instead exposes:
//
//   resolveAuth(env)   -> async { headers } and/or { binding }
//   buildRequests(cfg) -> Descriptor[]     ({ kind: "http", ... } or
//                                            { kind: "binding", ... })
//   parseResponses({ results, expectedVariants })
//                      -> { images, costUsd, blocked, blockReason, partial }
//
// The Worker (cloudflare-worker.js) owns the single dispatch path that
// executes descriptors via Promise.allSettled and folds the results back
// through parseResponses -- see addendum section 2.3. This module never
// calls fetch() or a binding's .run() itself.
//
// Only the workers_ai adapter is implemented in this slice (addendum
// section 4). openrouter, vertex, and the Kaplan proxy are deliberately
// absent from ENGINES until a later slice adds them.

const WORKERS_AI_MAX_PROMPT = 2048;

// Matched against a real captured Workers AI safety-rejection error. No such
// fixture has been captured yet, so this deliberately returns false rather
// than guess at a shape from memory (addendum section 4.2) -- a failure
// misreported as a safety block tells a player to rewrite a prompt that was
// fine. Replace the body once a real error is on hand, pinned by a test
// built from that fixture.
export function isWorkersAiSafetyRejection(_error) {
  return false;
}

export const ENGINES = {
  workers_ai: {
    async resolveAuth(env) {
      if (!env.AI) {
        throw new Error("Workers AI binding 'AI' is not configured in wrangler.jsonc");
      }
      return { binding: env.AI };
    },

    buildRequests({ model, prompt, variants, seeds, steps = 4 }) {
      if (!Array.isArray(seeds) || seeds.length !== variants) {
        throw new Error("workers_ai.buildRequests requires exactly one seed per variant");
      }
      const text = String(prompt).slice(0, WORKERS_AI_MAX_PROMPT);
      return seeds.map((seed) => ({
        kind: "binding",
        binding: "AI",
        model,
        payload: { prompt: text, steps, seed }
      }));
    },

    parseResponses({ results, expectedVariants }) {
      const images = [];
      let sawSafetyRejection = false;

      for (const result of results) {
        if (!result.ok) {
          if (isWorkersAiSafetyRejection(result.error)) sawSafetyRejection = true;
          continue;
        }
        const encoded = result.body?.image;
        if (typeof encoded === "string" && encoded.length > 0) {
          images.push({ mimeType: "image/jpeg", bytesBase64: encoded });
        }
      }

      return {
        images,
        costUsd: 0,
        blocked: images.length === 0 && sawSafetyRejection,
        blockReason: images.length === 0 && sawSafetyRejection
          ? "The image model declined that prompt."
          : null,
        partial: images.length > 0 && images.length < expectedVariants
      };
    }
  }
};
