// image-engine.js — Prompt Battle adapter layer.
//
// Pure functions only: no fetching, no side effects, no randomness. This is
// what lets test/image-engine.test.js run entirely from fixtures instead of
// a live provider, which CLAUDE.md forbids in tests. Seeds are generated by
// the caller (the Worker) and passed in, precisely so buildRequests stays
// deterministic.
//
// Contract: docs/superpowers/specs/2026-08-24-prompt-battle-free-engine-addendum.md
// section 2. That addendum corrects the base design's singular
// buildRequest/parseResponse pair (2026-08-17-prompt-battle-design.md
// section 7.3), which cannot express a provider that needs N calls to
// produce N variants without pushing I/O into this module. Each adapter
// instead exposes:
//
//   resolveAuth(env)   -> async { headers } and/or { binding }
//   buildRequests(cfg) -> Descriptor[]     ({ kind: "http", ... } or
//                                            { kind: "binding", ... })
//   parseResponses({ results, expectedVariants })
//                      -> { images, costUsd, blocked, blockReason, partial }
//
// The Worker (cloudflare-worker.js) owns the single dispatch path that
// executes descriptors via Promise.allSettled and folds the results back
// through parseResponses -- see addendum section 2.3. This module never
// calls fetch() or a binding's .run() itself.
//
// Adapter status: workers_ai, kaplan_proxy and openrouter are implemented
// (openrouter is not yet enabled in the Worker's allowlist); vertex is not
// yet present.

const WORKERS_AI_MAX_PROMPT = 2048;

// Per-model call profiles. These models do NOT share an input schema, and
// they reject unrecognised properties outright rather than ignoring them, so
// each payload has to be built to its own shape. Cloudflare's published
// schemas have now disagreed with the live API three times, so every entry
// here records what the API actually did.
//
//   flux-1-schnell  flat payload, `steps`; rejects `seed` outright
//                   ("Additional or unevaluated properties '/seed'")
//   lucid-origin    flat payload, `steps`; its two variants differ without a
//                   seed, so model non-determinism already supplies the
//                   diversity the game needs -- we never send `seed`
//   flux-2-klein-*  will not accept a JSON payload at all. It requires
//                   multipart/form-data: env.AI.run() is called with
//                   { multipart: { body, contentType } } where body is a
//                   form stream and contentType carries the MIME boundary.
//                   A plain object can never satisfy that, which is why both
//                   a flat payload and a { multipart: {...} } object were
//                   rejected with the same "required properties at '/' are
//                   'multipart'".
//
// `encoding` records that difference. This module still emits only inert
// data -- the FormData and its stream are constructed by the Worker in
// runBattleDescriptor(), because a ReadableStream is single-use and building
// one here would put I/O back into the pure module that the addendum's whole
// contract (section 2) exists to keep pure.
export const WORKERS_AI_PROFILES = {
  "@cf/black-forest-labs/flux-1-schnell": { stepsKey: "steps", steps: 4, encoding: "json" },
  "@cf/leonardo/lucid-origin": { stepsKey: "steps", steps: 20, encoding: "json" },
  "@cf/black-forest-labs/flux-2-klein-4b": { stepsKey: "num_steps", steps: 4, encoding: "multipart" },
  "@cf/black-forest-labs/flux-2-klein-9b": { stepsKey: "num_steps", steps: 4, encoding: "multipart" }
};

// An unlisted model gets schnell's shape, which is the conservative choice:
// a flat JSON payload with the most widely accepted parameter name.
const WORKERS_AI_DEFAULT_PROFILE = { stepsKey: "steps", steps: 4, encoding: "json" };

// Matched against a real captured Workers AI safety-rejection error. No such
// fixture has been captured yet, so this deliberately returns false rather
// than guess at a shape from memory (addendum section 4.2) -- a failure
// misreported as a safety block tells a player to rewrite a prompt that was
// fine. Replace the body once a real error is on hand, pinned by a test
// built from that fixture.
export function isWorkersAiSafetyRejection(_error) {
  return false;
}

// --- OpenRouter (issue #44) ---------------------------------------------
//
// POST https://openrouter.ai/api/v1/images, one request per variant: every
// Gemini image model on OpenRouter accepts only n: 1. Behaviour below follows
// OpenRouter's documentation as checked on 2026-10-05 (image generation,
// authentication, usage accounting, errors); none of it has been confirmed
// against the live API yet.
export const OPENROUTER_IMAGES_URL = "https://openrouter.ai/api/v1/images";

// Error codes that mean the model declined the prompt. Taken from
// OpenRouter's general error documentation; its image page shows no refusal,
// so the host test button has to confirm the real shape.
//
// Where the error body comes from: runBattleDescriptor() in
// cloudflare-worker.js turns a non-2xx response into
// { ok: false, status, error } with error.status set, but today it does not
// read the response body. This adapter reads OpenRouter's
// { error: { code, message } } envelope from result.error.body. The Worker
// ticket that enables openrouter must attach the parsed error body as
// error.body in runBattleDescriptor (and pass config.auth to buildRequests).
// Until then every OpenRouter failure is refused as an unaccounted outcome,
// which is the safe direction: an unknown charge is never assumed to be zero.
const OPENROUTER_REFUSAL_CODES = new Set(["content_policy_violation", "refusal"]);

// Base64 prefixes of the PNG, JPEG and WebP file signatures, used only when
// OpenRouter omits media_type (its docs say it may).
const OPENROUTER_BASE64_SIGNATURES = [
  ["iVBORw0KGgo", "image/png"],
  ["/9j/", "image/jpeg"],
  ["UklGR", "image/webp"]
];

function openRouterUnaccounted(detail) {
  return new Error(`Unaccounted OpenRouter outcome: ${detail}`);
}

function openRouterMimeType(entry) {
  const declared = entry.media_type;
  if (typeof declared === "string" && declared.trim() !== "") {
    return declared.startsWith("image/") ? declared : null;
  }
  for (const [prefix, mimeType] of OPENROUTER_BASE64_SIGNATURES) {
    if (entry.b64_json.startsWith(prefix)) return mimeType;
  }
  return null;
}

// A failed result is an unbilled OpenRouter error response only when it has
// a real non-2xx HTTP status AND carries OpenRouter's { error: { ... } }
// envelope at result.error.body (contract Decision 4). Anything else -- status
// 0 or none (fetch never got a response, or a 2xx body would not parse), or a
// non-2xx without that envelope (an edge timeout such as 524, or today's
// Worker, which drops the body) -- is an unknown charge.
function isOpenRouterErrorResponse(result) {
  const status = result.status;
  const isErrorStatus = Number.isInteger(status) && status >= 100 && status <= 599 && (status < 200 || status > 299);
  const envelope = result.error?.body?.error;
  return isErrorStatus && envelope !== null && typeof envelope === "object" && !Array.isArray(envelope);
}

export const ENGINES = {
  workers_ai: {
    async resolveAuth(env) {
      if (!env.AI) {
        throw new Error("Workers AI binding 'AI' is not configured in wrangler.jsonc");
      }
      return { binding: env.AI };
    },

    buildRequests({ model, prompt, variants, seeds, steps }) {
      if (!Array.isArray(seeds) || seeds.length !== variants) {
        throw new Error("workers_ai.buildRequests requires exactly one seed per variant");
      }
      const profile = WORKERS_AI_PROFILES[model] || WORKERS_AI_DEFAULT_PROFILE;
      // An omitted `steps` takes the model's profile default; an explicit
      // null suppresses the field even when the profile names one.
      const resolvedSteps = steps === undefined ? profile.steps : steps;
      const text = String(prompt).slice(0, WORKERS_AI_MAX_PROMPT);
      // `seeds` stays a required input -- it's still what pins the
      // descriptor count to `variants` and keeps this function
      // deterministic for tests -- but `seed` is never forwarded in the
      // payload. Verified live against the real API on 2026-08-24: it
      // rejects the call outright with "Additional or unevaluated
      // properties '/seed' at '/' not allowed", contradicting the addendum
      // spec's documented input contract (section 4.1). Whether repeated
      // identical calls still produce visually distinct variants without a
      // seed to vary is unverified; see the session handoff.
      // Built fresh per variant rather than shared by reference, so a
      // caller mutating one descriptor cannot reach the others.
      return seeds.map(() => {
        const fields = { prompt: text };
        if (profile.stepsKey && resolvedSteps !== null && resolvedSteps !== undefined) {
          fields[profile.stepsKey] = resolvedSteps;
        }
        return {
          kind: "binding",
          binding: "AI",
          model,
          encoding: profile.encoding,
          payload: fields
        };
      });
    },

    parseResponses({ results, expectedVariants }) {
      const images = [];
      let sawSafetyRejection = false;

      for (const result of results) {
        if (!result.ok) {
          if (isWorkersAiSafetyRejection(result.error)) sawSafetyRejection = true;
          continue;
        }
        const encoded = result.body?.image;
        if (typeof encoded === "string" && encoded.length > 0) {
          images.push({ mimeType: "image/jpeg", bytesBase64: encoded });
        }
      }

      return {
        images,
        costUsd: 0,
        blocked: images.length === 0 && sawSafetyRejection,
        blockReason: images.length === 0 && sawSafetyRejection
          ? "The image model declined that prompt."
          : null,
        partial: images.length > 0 && images.length < expectedVariants
      };
    }
  },

  kaplan_proxy: {
    async resolveAuth(env) {
      const base = env?.KAPLAN_PROXY_URL;
      if (typeof base !== "string" || base.trim() === "") {
        throw new Error("Kaplan proxy URL is not configured");
      }

      let url;
      try {
        const parsed = new URL(base);
        if (parsed.protocol !== "https:") {
          throw new Error("not https");
        }
        url = new URL("/generate", base).href;
      } catch {
        throw new Error("Kaplan proxy URL must be a valid HTTPS URL");
      }

      const secret = env?.KAPLAN_PROXY_SECRET;
      if (typeof secret !== "string" || secret.trim() === "") {
        throw new Error("Kaplan proxy secret is not configured");
      }

      return {
        url,
        headers: {
          Authorization: `Bearer ${secret}`
        }
      };
    },

    buildRequests(config) {
      if (!Number.isInteger(config?.variants) || config.variants < 1 || config.variants > 4) {
        throw new Error("kaplan_proxy.buildRequests requires variants to be an integer between 1 and 4");
      }

      const auth = config.auth;
      if (!auth || typeof auth !== "object" || typeof auth.url !== "string" || typeof auth.headers !== "object") {
        throw new Error("kaplan_proxy.buildRequests requires the resolved auth object from resolveAuth");
      }

      return [{
        kind: "http",
        url: auth.url,
        headers: {
          "content-type": "application/json",
          ...auth.headers
        },
        body: {
          prompt: config.prompt,
          model: config.model,
          variants: config.variants
        }
      }];
    },

    parseResponses({ results, expectedVariants }) {
      if (!Number.isInteger(expectedVariants) || expectedVariants < 1 || expectedVariants > 4) {
        throw new Error("kaplan_proxy.parseResponses requires expectedVariants to be an integer between 1 and 4");
      }

      if (!Array.isArray(results) || results.length === 0) {
        throw new Error("Unaccounted proxy outcome: Kaplan proxy returned no fulfilled results");
      }

      let costUsd = 0;
      const images = [];
      let explicitBlocked = false;
      let explicitBlockReason = null;

      for (const result of results) {
        if (!result || result.ok !== true) {
          throw new Error("Unaccounted proxy outcome: Kaplan proxy request did not fulfill cleanly");
        }

        const body = result.body;
        if (!body || typeof body !== "object") {
          throw new Error("Unaccounted proxy outcome: Kaplan proxy fulfilled without a parseable body");
        }

        const cost = body.costUsd;
        if (typeof cost !== "number" || !Number.isFinite(cost) || cost < 0) {
          throw new Error("Unaccounted proxy outcome: Kaplan proxy fulfilled without a valid numeric costUsd");
        }

        costUsd += cost;
        if (!Number.isFinite(costUsd)) {
          throw new Error("Unaccounted proxy outcome: Kaplan proxy cost total is not finite");
        }

        const rawImages = Array.isArray(body.images) ? body.images : [];
        for (const entry of rawImages) {
          if (!entry || typeof entry !== "object") continue;
          const mimeType = entry.mimeType;
          const bytesBase64 = entry.bytesBase64;
          if (typeof mimeType !== "string" || mimeType.trim() === "" || !mimeType.startsWith("image/")) continue;
          if (typeof bytesBase64 !== "string" || bytesBase64.trim() === "") continue;
          images.push({ mimeType, bytesBase64 });
        }

        if (body.blocked === true) {
          explicitBlocked = true;
        }
        if (typeof body.blockReason === "string" && body.blockReason.trim() !== "") {
          if (explicitBlockReason === null) {
            explicitBlockReason = body.blockReason;
          }
        }
      }

      const imageCount = images.length;
      const blocked = imageCount === 0 && (explicitBlocked || explicitBlockReason !== null);
      const blockReason = blocked ? explicitBlockReason : null;

      return {
        images,
        costUsd,
        blocked,
        blockReason,
        partial: imageCount > 0 && imageCount < expectedVariants
      };
    }
  },

  openrouter: {
    async resolveAuth(env) {
      const key = env?.OPENROUTER_API_KEY;
      if (typeof key !== "string" || key.trim() === "") {
        throw new Error("OPENROUTER_API_KEY is not configured");
      }
      return {
        url: OPENROUTER_IMAGES_URL,
        headers: {
          Authorization: `Bearer ${key.trim()}`
        }
      };
    },

    buildRequests(config) {
      if (!Number.isInteger(config?.variants) || config.variants < 1 || config.variants > 4) {
        throw new Error("openrouter.buildRequests requires variants to be an integer between 1 and 4");
      }

      const auth = config.auth;
      if (!auth || typeof auth !== "object" || typeof auth.url !== "string" || !auth.headers || typeof auth.headers !== "object") {
        throw new Error("openrouter.buildRequests requires the resolved auth object from resolveAuth");
      }

      // Seeds are deliberately not forwarded, nor any other optional field:
      // the body is model, prompt and n: 1, plus resolution / output_format
      // only when the round sets them. Built fresh per variant so a caller
      // mutating one descriptor cannot reach the others.
      const descriptors = [];
      for (let index = 0; index < config.variants; index += 1) {
        const body = { model: config.model, prompt: config.prompt, n: 1 };
        if (config.resolution !== undefined && config.resolution !== null) {
          body.resolution = config.resolution;
        }
        if (config.outputFormat !== undefined && config.outputFormat !== null) {
          body.output_format = config.outputFormat;
        }
        descriptors.push({
          kind: "http",
          url: auth.url,
          headers: {
            "content-type": "application/json",
            ...auth.headers
          },
          body
        });
      }
      return descriptors;
    },

    parseResponses({ results, expectedVariants }) {
      if (!Number.isInteger(expectedVariants) || expectedVariants < 1 || expectedVariants > 4) {
        throw new Error("openrouter.parseResponses requires expectedVariants to be an integer between 1 and 4");
      }

      if (!Array.isArray(results) || results.length === 0) {
        throw openRouterUnaccounted("no request results were returned");
      }

      let costUsd = 0;
      const images = [];
      let refusalMessage = null;
      let sawRefusal = false;

      for (const result of results) {
        if (!result || typeof result !== "object") {
          throw openRouterUnaccounted("a request result is missing");
        }

        if (result.ok !== true) {
          // OpenRouter bills all-or-nothing: an error response is not
          // charged and adds no images. Anything else is an unknown charge,
          // which is never assumed to be zero.
          if (!isOpenRouterErrorResponse(result)) {
            throw openRouterUnaccounted("a request got no response or no OpenRouter error body, so its cost is unknown");
          }
          const providerError = result.error.body.error;
          if (!sawRefusal && OPENROUTER_REFUSAL_CODES.has(providerError.code)) {
            sawRefusal = true;
            refusalMessage = typeof providerError.message === "string" && providerError.message.trim() !== ""
              ? providerError.message
              : "The image model declined that prompt.";
          }
          continue;
        }

        const body = result.body;
        if (!body || typeof body !== "object") {
          throw openRouterUnaccounted("a successful response has no parseable body");
        }

        const cost = body.usage?.cost;
        if (typeof cost !== "number" || !Number.isFinite(cost) || cost < 0) {
          throw openRouterUnaccounted("a successful response has no valid usage.cost");
        }
        costUsd += cost;
        if (!Number.isFinite(costUsd)) {
          throw openRouterUnaccounted("the cost total is not finite");
        }

        const entries = Array.isArray(body.data) ? body.data : [];
        for (const entry of entries) {
          if (!entry || typeof entry !== "object") continue;
          if (typeof entry.b64_json !== "string" || entry.b64_json.trim() === "") continue;
          const mimeType = openRouterMimeType(entry);
          if (mimeType === null) continue;
          images.push({ mimeType, bytesBase64: entry.b64_json });
        }
      }

      const imageCount = images.length;
      const blocked = imageCount === 0 && sawRefusal;

      return {
        images,
        costUsd,
        blocked,
        blockReason: blocked ? refusalMessage : null,
        partial: imageCount > 0 && imageCount < expectedVariants
      };
    }
  }
};
